Caja/Caja/Controllers/FacturacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Caja.Datos;
using Caja.Models;
using Oracle.ManagedDataAccess.Client;
using Caja.Class;
using CrystalDecisions;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using System.IO;
using BarcodeLib;
using System.Drawing.Imaging;
using System.Data;
using System.Net.Mail;
using System.Net;
using System.Security.Cryptography.X509Certificates;
using System.Net.Security;

namespace Caja.Controllers
{
    public class FacturacionController : Controller
    {
        decimal Suc, CodPtoVta, CodigoTipoComprobante, CotizacionMoneda,
            ImporteOtrosTributos, ImporteSubtotal,
            ItemsItemCantidad, NUMEROComprobante, NUMEROPuntoVenta, SubTotalesItemCantidad, ImporteTotal;
        int CajaNum, Turno, CajaEstado, CodigoConcepto, OtrosTributosItemCantidad, CompAsociadosItemCantidad, CodigoTipoDocumento,
            TIPO_COMPROBANTE, Emision, P_Numero, TIPO_PEDIDO, bandera, PEDIDO_NUMERO, P_ID, SumaPar, SumaImpar, ProductoSum,
            DivEntera, DigVerificador, TipoCompAsos, EmisionCompAsos, NumCompAsos;
        long valor, P_ID_VENTA;
        Int64 chbSelect;
        string FechaApertura, CodigoMoneda, FEchaEmision, FEchaservicioDesde, FEchaServicioHasta, FEchaVencimiento, FEchaVencimientoPago,
            NUMERODocumento, Obervaciones, MENSAJE, P_FEchaEmision, P_NUMERODocumento, Decimales, Referencia, totLetras,
            RetAfip, DirVacia;
        string v_empresa_inicio, v_empresa_abrev, v_empresa_nomb, v_empresa_cuit, v_empresacat_iva, v_empresa_ing_bru, v_fe_ubicacion_cert, v_fe_clave;
        int v_codigo_empresa;
        double v_fe_cuit;

        double ImporteGravado, ImporteNoGravado, ImporteExento, P_TOTAL;
        String sConnectionString = System.Web.HttpContext.Current.Session["Connection"] as string;
        byte[] CodigoBarras;

        DataSet dsSuc = new DataSet();
        DataSet dsPto = new DataSet();

        public Class.Conv converter = new Class.Conv();

        Datos.dsTelecomTableAdapters.COMPROBANTE_PDFTableAdapter taCompr = new Datos.dsTelecomTableAdapters.COMPROBANTE_PDFTableAdapter();
        Datos.dsTelecomTableAdapters.OPERACIONES_CAJATableAdapter taOpCaja = new Datos.dsTelecomTableAdapters.OPERACIONES_CAJATableAdapter();
        Datos.dsTelecomTableAdapters.SUCURSALESTableAdapter taSucursal = new Datos.dsTelecomTableAdapters.SUCURSALESTableAdapter();
        Datos.dsTelecomTableAdapters.PTOS_VTATableAdapter taPtoVta = new Datos.dsTelecomTableAdapters.PTOS_VTATableAdapter();
        Datos.dsTelecomTableAdapters.CajaNumeroTableAdapter taCajaNum = new Datos.dsTelecomTableAdapters.CajaNumeroTableAdapter();
        Datos.dsTelecomTableAdapters.CajaEncabezadoTableAdapter taEncabezado = new Datos.dsTelecomTableAdapters.CajaEncabezadoTableAdapter();
        Datos.dsTelecomTableAdapters.USUARIOSTableAdapter taUser = new Datos.dsTelecomTableAdapters.USUARIOSTableAdapter();
        Datos.dsTelecomTableAdapters.FE_VENTA_ITEMSTableAdapter taItemsVta = new Datos.dsTelecomTableAdapters.FE_VENTA_ITEMSTableAdapter();
        Datos.dsTelecomTableAdapters.EMPRESASTableAdapter taEmpresas = new Datos.dsTelecomTableAdapters.EMPRESASTableAdapter();
        Datos.dsTelecomTableAdapters.CAJA_JERARQUIATableAdapter taJerarquia = new Datos.dsTelecomTableAdapters.CAJA_JERARQUIATableAdapter();

        Datos.dsTelecom dsTelecom = new Datos.dsTelecom();

        List<FacturacionViewModel.OpCaja> GridOperaciones = new List<FacturacionViewModel.OpCaja>();
        List<FacturacionViewModel.Sucursal> Sucursal = new List<FacturacionViewModel.Sucursal>();
        List<FacturacionViewModel.PtosVta> PtoVta = new List<FacturacionViewModel.PtosVta>();

        public int V_codigo_empresa
        {
            get
            {
                return v_codigo_empresa;
            }

            set
            {
                v_codigo_empresa = value;
            }
        }

        void CargaDatosCaja(int CajaNum)
        {
            try
            {
                double TotEfectivo = 0, TotTarjeta = 0, TotTotal;
                //Consulta

                taOpCaja.FillByNumCaja(dsTelecom.OPERACIONES_CAJA, CajaNum);
                for (int i = 0; i < dsTelecom.OPERACIONES_CAJA.Count(); i++)
                {
                    GridOperaciones.Add(new
                    FacturacionViewModel.OpCaja
                    {
                        Id = dsTelecom.OPERACIONES_CAJA[i].ID,
                        Fecha = dsTelecom.OPERACIONES_CAJA[i].FECHA.ToString("dd/MM/yyyy"),
                        Numero = int.Parse(dsTelecom.OPERACIONES_CAJA[i].NUMERO),
                        Abreviatura = dsTelecom.OPERACIONES_CAJA[i].ABREVIATURA.ToString(),
                        Descripcion = dsTelecom.OPERACIONES_CAJA[i].DESCRIPCION.ToString(),
                        Efectivo = double.Parse(dsTelecom.OPERACIONES_CAJA[i].EFECTIVO.ToString()),
                        Tarjeta = double.Parse(dsTelecom.OPERACIONES_CAJA[i].TARJETA.ToString()),
                        Total = double.Parse(dsTelecom.OPERACIONES_CAJA[i].TOTAL.ToString()),
                    });
                    TotEfectivo = TotEfectivo + double.Parse(dsTelecom.OPERACIONES_CAJA[i].EFECTIVO.ToString());
                    TotTarjeta = TotTarjeta + double.Parse(dsTelecom.OPERACIONES_CAJA[i].TARJETA.ToString());
                }
                TotTotal = TotTarjeta + TotEfectivo;
                ViewData["Efectivo"] = TotEfectivo;
                ViewData["Tarjeta"] = TotTarjeta;
                ViewData["TotTotal"] = TotTotal;
            }
            catch (Exception)
            {

                throw;
            }
        }

        public void PermisoNotaC()
        {
            try
            {
                //Permisos Usuario
                OracleConnection conn = new OracleConnection(sConnectionString);
                conn.Open();

                OracleCommand Scmd = new OracleCommand();
                Scmd.Connection = conn;
                Scmd.CommandText = "TELECOM.SECURITY_PACK.tiene_permiso_n";
                Scmd.CommandType = System.Data.CommandType.StoredProcedure;
                Scmd.Parameters.Add("returnVal", OracleDbType.Int64, 999999);
                Scmd.Parameters["returnVal"].Direction = System.Data.ParameterDirection.ReturnValue;
                Scmd.Parameters.Add("pid_funcion", 28);
                Scmd.Parameters.Add("pusuario", System.Web.HttpContext.Current.Session["usuario"].ToString().ToUpper());

                Scmd.ExecuteNonQuery();
                int NCPermiso = int.Parse(Scmd.Parameters["returnVal"].Value.ToString());
                ViewData["NCPermiso"] = NCPermiso;

                conn.Close();
            }
            catch (Exception)
            {

                throw;
            }
        }

        void CargaSuc()
        {
            try
            {
                PermisoNotaC();

                OracleConnection conn = new OracleConnection(sConnectionString);
                conn.Open();
                OracleCommand fscmd = new OracleCommand();
                fscmd.Connection = conn;
                fscmd.CommandText = "Select CODIGO, NOMBRE from Telecom.Sucursales SU where Inhabilitado is null AND TELECOM.SECURITY_PACK.VALIDAR_FILTRO(:Usuario, 'CODIGO_SUP_GES', SU.CODIGO) = 1";
                fscmd.CommandType = System.Data.CommandType.Text;
                fscmd.Parameters.Add("?Usuario", OracleDbType.NVarchar2, 255);
                fscmd.Parameters["?Usuario"].Value = System.Web.HttpContext.Current.Session["usuario"].ToString().ToUpper();
                fscmd.ExecuteNonQuery();

                conn.Close();

                OracleDataAdapter da = new OracleDataAdapter(fscmd);
                da.Fill(dsSuc, "Sucursal");

                Array DatoSuc = dsSuc.Tables["Sucursal"].Rows[0].ItemArray;
                Suc = decimal.Parse(DatoSuc.GetValue(0).ToString());
            }
            catch (Exception)
            {

                throw;
            }
        }
        public void CargaddlSuc()
        {
            try
            {
                OracleConnection conn = new OracleConnection(sConnectionString);
                conn.Open();
                OracleCommand fscmd = new OracleCommand();
                fscmd.Connection = conn;
                fscmd.CommandText = "Select CODIGO, NOMBRE from Telecom.Sucursales SU where Inhabilitado is null AND TELECOM.SECURITY_PACK.VALIDAR_FILTRO(:Usuario, 'CODIGO_SUP_GES', SU.CODIGO) = 1";
                fscmd.CommandType = System.Data.CommandType.Text;
                fscmd.Parameters.Add("?Usuario", OracleDbType.NVarchar2, 255);
                fscmd.Parameters["?Usuario"].Value = System.Web.HttpContext.Current.Session["usuario"].ToString().ToUpper();
                fscmd.ExecuteNonQuery();

                conn.Close();

                OracleDataAdapter da = new OracleDataAdapter(fscmd);
                da.Fill(dsSuc, "Sucursal");

                //Suc y Pto Vta Usuario
                //Suc = dsTelecom.USUARIOS[0].CODIGO_SUP_GES;
                //Session["Sucursal"] = Suc;
                //CodPtoVta = dsTelecom.USUARIOS[0].PTO_VTA;
                //Session["PtoVta"] = CodPtoVta;
                //DropDown Sucursal                
                Array DatoSuc = dsSuc.Tables["Sucursal"].Rows[0].ItemArray;
                Suc = decimal.Parse(DatoSuc.GetValue(0).ToString());

                taSucursal.Fill(dsTelecom.SUCURSALES);
                var modelo = new FacturacionViewModel.Sucursal();
                modelo.LstSucursal = new List<SelectListItem>();
                List<SelectListItem> Sucursales = new List<SelectListItem>();
                foreach (DataRow drow in dsSuc.Tables["Sucursal"].Rows)
                {
                    modelo.LstSucursal.Add(new SelectListItem() { Text = drow[1].ToString(), Value = drow[0].ToString() });
                }

Caja/Caja/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Caja.Models;
using Caja.Datos;

namespace Caja.Controllers
{
    public class InicioController : Controller
    {
        private string Autor;

        public string MensajeMotivador { get; set; }

        // GET: Inicio
        public ActionResult Index()
        {
            LoginController lo = new LoginController();
            lo.SmartLogin("~/Inicio/Index", "VALIDA");
            if (System.Web.HttpContext.Current.Session["usuario"] != null)
            {

                Datos.UsuarioTableAdapters.MENSAJES_MOTIVADORESTableAdapter mMot = new Datos.UsuarioTableAdapters.MENSAJES_MOTIVADORESTableAdapter();
                Datos.Usuario.MENSAJES_MOTIVADORESDataTable mensajes = new Datos.Usuario.MENSAJES_MOTIVADORESDataTable();
                mMot.Fill(mensajes);
                string mensaje = mensajes[0].VALOR;
                string autor = mensajes[0].DESCRIPCION;
                var model = new Inicio(MensajeMotivador = mensaje, Autor = autor);
                TempData["mensajeMot"] = model.MensajeMotivador;
                TempData["autor"] = model.Autor;
                return View();
            }
            else
            {
                return lo.VerificaConexion("~/Inicio/Index");
            }
        }
    }
}

Caja/Caja/Controllers/PruebaServicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Caja.Models.Class;
using Caja.Class;

namespace Caja.Controllers
{
    public class PruebaServicioController : Controller
    {
        // GET: PruebaServicio
        public ActionResult Index()
        {          
           
            return View();        
        }
        [HttpPost]
        public ActionResult btnPrueba()
        {
            var dll = new PruebaServicioViewModels();
            var Afip = new Afip();
            //ViewBag.Mensaje = Afip.CAE();
            //Afip.UltimoComprobante();
            
            return View("Index");
        }
        public ActionResult btnConsulta()
        {
            var dll = new PruebaServicioViewModels();
            var afip = new Afip();
            //afip.ConsultaDatos();

            return View("Index");
        }
    }
}

Caja/Caja/Views/Shared/SidebarMenu.cshtml
@model IEnumerable <Caja.Models.MenuItem> 
<!-- Sidebar user panel -->
<div class="user-panel">
    <div class="pull-left image">
        <img src=@Url.Content("~/Content/imagenes/bb.png") class="img-circle" alt="User Image">
    </div>
    <div class="pull-left info">
        <p>@System.Web.HttpContext.Current.Session["usuario"]</p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
    </div>
</div>
<!-- search form -->
<form action="#" method="get" class="sidebar-form">
    <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search...">
        <span class="input-group-btn">
            <button type="submit" name="buscar..." id="search-btn" class="btn btn-flat">
                <i class="fa fa-search"></i>
            </button>
        </span>
    </div>
</form>
<!-- /.search form -->
<!-- sidebar menu: : style can be found in sidebar.less -->
<ul class="sidebar-menu" data-widget="tree">
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            if (item.SubNiveles == 0)
            {
                <li>
                    <a href="@item.Link">
                        <i class="@item.Class"></i> <span>@item.LinkName</span>
                    </a>
                </li>
            }
            else
            {
                <li class="treeview">
                    <a href="#">
                        <i class="@item.Class"></i> <span>@item.LinkName</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        @for (int i = 0; i < item.SubNiveles; i++)
                        {
                            var item2 = item.SubMenu[i];
                            <li><a href="@item2.Link"><i class="@item2.Class"></i> @item2.LinkName</a></li>
                        }
                    </ul>
                </li>
            }
        }
    }
</ul>
<!--<ul class="sidebar-menu" data-widget="tree">
    <li>
        <a href="@Url.Action("ValidaConexion", "Login")">
            <i class="fa fa-home"></i> <span>Inicio</span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "Inicio")">
            <i class="fa fa-home"></i> <span>Inicio</span>
        </a>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-dashboard"></i> <span>Caja</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="@Url.Action("Index", "Facturacion")"><i class="fa fa-circle-o"></i> Operaciones de Caja</a></li>
            <li><a href="@Url.Action("Index", "PruebaServicio")"><i class="fa fa-circle-o"></i> Prueba Servicio</a></li>

        </ul>


    </li>
    <!--<li class="treeview">
        <a href="#">
            <i class="fa fa-files-o"></i>
            <span>Layout Options</span>
            <span class="pull-right-container">
                <span class="label label-primary pull-right">4</span>
            </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="~/Content/pages/layout/top-nav.html"><i class="fa fa-circle-o"></i> Top Navigation</a></li>
            <li><a href="~/Content/pages/layout/boxed.html"><i class="fa fa-circle-o"></i> Boxed</a></li>
            <li><a href="~/Content/pages/layout/fixed.html"><i class="fa fa-circle-o"></i> Fixed</a></li>
            <li><a href="~/Content/pages/layout/collapsed-sidebar.html"><i class="fa fa-circle-o"></i> Collapsed Sidebar</a></li>
        </ul>
    </li>
    <li>
        <a href="~/Content/pages/widgets.html">
            <i class="fa fa-th"></i> <span>Widgets</span>
            <span class="pull-right-container">
                <small class="label pull-right bg-green">new</small>
            </span>
        </a>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-pie-chart"></i>
            <span>Charts</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="~/Content/pages/charts/chartjs.html"><i class="fa fa-circle-o"></i> ChartJS</a></li>
            <li><a href="~/Content/pages/charts/morris.html"><i class="fa fa-circle-o"></i> Morris</a></li>
            <li><a href="~/Content/pages/charts/flot.html"><i class="fa fa-circle-o"></i> Flot</a></li>
            <li><a href="~/Content/pages/charts/inline.html"><i class="fa fa-circle-o"></i> Inline charts</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-laptop"></i>
            <span>UI Elements</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="~/Content/pages/UI/general.html"><i class="fa fa-circle-o"></i> General</a></li>
            <li><a href="~/Content/pages/UI/icons.html"><i class="fa fa-circle-o"></i> Icons</a></li>
            <li><a href="~/Content/pages/UI/buttons.html"><i class="fa fa-circle-o"></i> Buttons</a></li>
            <li><a href="~/Content/pages/UI/sliders.html"><i class="fa fa-circle-o"></i> Sliders</a></li>
            <li><a href="~/Content/pages/UI/timeline.html"><i class="fa fa-circle-o"></i> Timeline</a></li>
            <li><a href="~/Content/pages/UI/modals.html"><i class="fa fa-circle-o"></i> Modals</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-edit"></i> <span>Forms</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="~/Content/pages/forms/general.html"><i class="fa fa-circle-o"></i> General Elements</a></li>
            <li><a href="~/Content/pages/forms/advanced.html"><i class="fa fa-circle-o"></i> Advanced Elements</a></li>
            <li><a href="~/Content/pages/forms/editors.html"><i class="fa fa-circle-o"></i> Editors</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-table"></i> <span>Tables</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="~/Content/pages/tables/simple.html"><i class="fa fa-circle-o"></i> Simple tables</a></li>
            <li><a href="~/Content/pages/tables/data.html"><i class="fa fa-circle-o"></i> Data tables</a></li>
        </ul>
    </li>
    <li>
        <a href="~/Content/pages/calendar.html">
            <i class="fa fa-calendar"></i> <span>Calendar</span>
            <span class="pull-right-container">
                <small class="label pull-right bg-red">3</small>
                <small class="label pull-right bg-blue">17</small>
            </span>
        </a>
    </li>
    <li>
        <a href="~/Content/pages/mailbox/mailbox.html">
            <i class="fa fa-envelope"></i> <span>Mailbox</span>
            <span class="pull-right-container">
                <small class="label pull-right bg-yellow">12</small>
                <small class="label pull-right bg-green">16</small>
                <small class="label pull-right bg-red">5</small>
            </span>
        </a>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-folder"></i> <span>Examples</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="~/Content/pages/examples/invoice.html"><i class="fa fa-circle-o"></i> Invoice</a></li>
            <li><a href="~/Content/pages/examples/profile.html"><i class="fa fa-circle-o"></i> Profile</a></li>
            <li><a href="~/Content/pages/examples/login.html"><i class="fa fa-circle-o"></i> Login</a></li>
            <li><a href="~/Content/pages/examples/register.html"><i class="fa fa-circle-o"></i> Register</a></li>
            <li><a href="~/Content/pages/examples/lockscreen.html"><i class="fa fa-circle-o"></i> Lockscreen</a></li>
            <li><a href="~/Content/pages/examples/404.html"><i class="fa fa-circle-o"></i> 404 Error</a></li>
            <li><a href="~/Content/pages/examples/500.html"><i class="fa fa-circle-o"></i> 500 Error</a></li>
            <li><a href="~/Content/pages/examples/blank.html"><i class="fa fa-circle-o"></i> Blank Page</a></li>
            <li><a href="~/Content/pages/examples/pace.html"><i class="fa fa-circle-o"></i> Pace Page</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-share"></i> <span>Multilevel</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-circle-o"></i> Level One
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-circle-o"></i> Level Two
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                            <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
        </ul>
    </li>
    <li><a href="https://adminlte.io/docs"><i class="fa fa-book"></i> <span>Documentation</span></a></li>
    <li class="header">LABELS</li>
    <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
    <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
    <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>-->
</ul>